services:
  postgres:
    image: postgres:15
    container_name: plataforma_voluntariado_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mi_password_123
      POSTGRES_DB: plataforma_voluntariado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./02_funciones.sql:/docker-entrypoint-initdb.d/02_funciones.sql
      - ./03_seed_data.sql:/docker-entrypoint-initdb.d/03_seed_data.sql
      - ./04_consultas_y_reportes.sql:/docker-entrypoint-initdb.d/04_consultas_y_reportes.sql

volumes:
  postgres_data:
